map_type: costmap

obstacle_range: 5.0 # default 0.0 (The maximum range in meters at which to insert obstacles into the costmap using sensor data. )
raytrace_range: 8.0 # defautl 0.0 (The maximum range in meters at which to raytrace out obstacles from the map using sensor data.)
 
transform_tolerance: 0.2 # default 0.0

initial_pose_x: 0.0 # added 
initial_pose_y: 0.0 # added 
initial_pose_a: -0.785 # added


robot_radius: 0.23 
inflation_radius: 0.23 # default was

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
